package org.example.esubmission.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Represents an assignment in the e-submission system.
 * <p>
 * This entity is mapped to the {@code assignments} table in the database
 * and stores information such as title, description, teacher, class, and deadlines.
 * </p>
 *
 * @author Mugisha Ivan Bright
 */
@Entity
@Table(name = "assignments")
public class Assignment {

    /**
     * Unique identifier for the assignment.
     * <p>
     * Automatically generated by the database using identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the assignment.
     * <p>
     * Cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private String title;

    /**
     * Description of the assignment.
     * <p>
     * Stored as {@code TEXT} in the database.
     * </p>
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * The teacher who created the assignment.
     * <p>
     * Represents a many-to-one relationship with {@link User}.
     * Cannot be null.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "teacher_id", nullable = false)
    private User teacher;

    /**
     * Name of the class for which this assignment is assigned.
     * <p>
     * Cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private String className;

    /**
     * Deadline for the assignment submission.
     * <p>
     * Cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private LocalDateTime deadline;

    /**
     * Timestamp when the assignment was created.
     * <p>
     * Defaults to the current date and time when the object is created.
     * Cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    // ------------------- Getters and Setters -------------------

    /**
     * Returns the unique identifier of the assignment.
     *
     * @return the assignment ID
     */
    public Long getId() { return id; }

    /**
     * Sets the unique identifier of the assignment.
     *
     * @param id the assignment ID to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Returns the title of the assignment.
     *
     * @return the title
     */
    public String getTitle() { return title; }

    /**
     * Sets the title of the assignment.
     *
     * @param title the title to set
     */
    public void setTitle(String title) { this.title = title; }

    /**
     * Returns the description of the assignment.
     *
     * @return the description
     */
    public String getDescription() { return description; }

    /**
     * Sets the description of the assignment.
     *
     * @param description the description to set
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * Returns the teacher who created the assignment.
     *
     * @return the teacher
     */
    public User getTeacher() { return teacher; }

    /**
     * Sets the teacher who created the assignment.
     *
     * @param teacher the teacher to set
     */
    public void setTeacher(User teacher) { this.teacher = teacher; }

    /**
     * Returns the class name for which the assignment is assigned.
     *
     * @return the class name
     */
    public String getClassName() { return className; }

    /**
     * Sets the class name for which the assignment is assigned.
     *
     * @param className the class name to set
     */
    public void setClassName(String className) { this.className = className; }

    /**
     * Returns the deadline of the assignment.
     *
     * @return the deadline
     */
    public LocalDateTime getDeadline() { return deadline; }

    /**
     * Sets the deadline of the assignment.
     *
     * @param deadline the deadline to set
     */
    public void setDeadline(LocalDateTime deadline) { this.deadline = deadline; }

    /**
     * Returns the creation timestamp of the assignment.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /**
     * Sets the creation timestamp of the assignment.
     *
     * @param createdAt the timestamp to set
     */
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    /**
     * Returns a human-readable string representation of the deadline.
     * <p>
     * Format: "MMM dd" (e.g., "Oct 24").
     * </p>
     *
     * @return the formatted deadline string
     */
    public String getFormattedDeadline() {
        if (deadline == null) return "No Deadline";
        return deadline.format(java.time.format.DateTimeFormatter.ofPattern("MMM dd"));
    }

    /**
     * Returns a human-readable string representation of the creation timestamp.
     * <p>
     * Format: "MMM dd, yyyy" (e.g., "Oct 24, 2023").
     * </p>
     *
     * @return the formatted creation timestamp
     */
    public String getFormattedCreatedAt() {
        if (createdAt == null) return "";
        return createdAt.format(java.time.format.DateTimeFormatter.ofPattern("MMM dd, yyyy"));
    }
}
