package org.example.esubmission.model;

import jakarta.persistence.*;
/**
 * Represents the allocation of a student to a class under a specific teacher.
 * <p>
 * This entity is mapped to the {@code student_classes} table in the database and
 * stores the relationship between students, teachers, and their assigned classes.
 * </p>
 *
 * @author Mugisha Ivan Bright
 */
@Entity
@Table(name = "student_classes")
public class StudentClass {
    /**
     * Unique identifier for the student-class allocation.
     * <p>
     * Automatically generated by the database using identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The student enrolled in the class.
     * <p>
     * Represents a many-to-one relationship to {@link User}.
     * Cannot be null.
     * @see User#getEmail()
     * </p>
     */

    @ManyToOne
    @JoinColumn(name = "student_id", nullable = false)
    private User student;

    /**
     * The name of the class the student is enrolled in.
     * <p>
     * Cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private String className;

    /**
     * The teacher responsible for the class.
     * <p>
     * Represents a many-to-one relationship to {@link User}.
     * Cannot be null.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "teacher_id", nullable = false)
    private User teacher;

    // Getters and Setters
    /**
     * Returns the unique identifier of the allocation.
     *
     * @return the allocation ID
     */
    public Long getId() { return id; }
    /**
     * Sets the unique identifier of the allocation.
     *
     * @param id the allocation ID to set
     */
    public void setId(Long id) { this.id = id; }
    /**
     * Returns the student associated with this allocation.
     *
     * @return the student
     */
    public User getStudent() { return student; }
    /**
     * Sets the student associated with this allocation.
     *
     * @param student the student to set
     */
    public void setStudent(User student) { this.student = student; }

    /**
     * Returns the name of the class.
     *
     * @return the class name
     */
    public String getClassName() { return className; }
    /**
     * Sets the name of the class.
     *
     * @param className the class name to set
     */
    public void setClassName(String className) { this.className = className; }
    /**
     * Returns the teacher responsible for the class.
     *
     * @return the teacher
     */
    public User getTeacher() { return teacher; }
    /**
     * Sets the teacher responsible for the class.
     *
     * @param teacher the teacher to set
     */
    public void setTeacher(User teacher) { this.teacher = teacher; }
}
