package org.example.esubmission.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Represents a submission of an assignment by a student.
 * <p>
 * This entity is mapped to the {@code submissions} table in the database and
 * stores details about the assignment, student, content, file, grade, and feedback.
 * </p>
 */
@Entity
@Table(name = "submissions")
public class Submission {

    /**
     * Unique identifier for the submission.
     * <p>
     * This value is automatically generated by the database using identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The assignment associated with this submission.
     * <p>
     * Represents a many-to-one relationship to {@link Assignment}.
     * Cannot be null.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "assignment_id", nullable = false)
    private Assignment assignment;

    /**
     * The student who made this submission.
     * <p>
     * Represents a many-to-one relationship to {@link User}.
     * Cannot be null.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "student_id", nullable = false)
    private User student;

    /**
     * The textual content of the submission.
     * <p>
     * Stored as {@code TEXT} in the database.
     * </p>
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    /**
     * URL of the file uploaded with the submission, if any.
     */
    @Column
    private String fileUrl;

    /**
     * The date and time when the submission was made.
     * <p>
     * Defaults to the current time at creation.
     * </p>
     */
    @Column(nullable = false)
    private LocalDateTime submittedAt = LocalDateTime.now();

    /**
     * The grade assigned to the submission.
     * <p>
     * Can be {@code null} if the submission has not been graded yet.
     * </p>
     */
    @Column
    private Integer grade;

    /**
     * Feedback provided for the submission.
     * <p>
     * Stored as {@code TEXT} in the database.
     * Can be {@code null} if no feedback has been given yet.
     * </p>
     */
    @Column(columnDefinition = "TEXT")
    private String feedback;

    // ------------------- Getters and Setters -------------------

    /**
     * Returns the unique identifier of the submission.
     *
     * @return the submission ID
     */
    public Long getId() { return id; }

    /**
     * Sets the unique identifier of the submission.
     *
     * @param id the submission ID to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Returns the assignment associated with this submission.
     *
     * @return the assignment
     */
    public Assignment getAssignment() { return assignment; }

    /**
     * Sets the assignment associated with this submission.
     *
     * @param assignment the assignment to set
     */
    public void setAssignment(Assignment assignment) { this.assignment = assignment; }

    /**
     * Returns the student who submitted this assignment.
     *
     * @return the student
     */
    public User getStudent() { return student; }

    /**
     * Sets the student who submitted this assignment.
     *
     * @param student the student to set
     */
    public void setStudent(User student) { this.student = student; }

    /**
     * Returns the textual content of the submission.
     *
     * @return the content
     */
    public String getContent() { return content; }

    /**
     * Sets the textual content of the submission.
     *
     * @param content the content to set
     */
    public void setContent(String content) { this.content = content; }

    /**
     * Returns the URL of the file uploaded with the submission.
     *
     * @return the file URL
     */
    public String getFileUrl() { return fileUrl; }

    /**
     * Sets the URL of the file uploaded with the submission.
     *
     * @param fileUrl the file URL to set
     */
    public void setFileUrl(String fileUrl) { this.fileUrl = fileUrl; }

    /**
     * Returns the date and time when the submission was made.
     *
     * @return the submission timestamp
     */
    public LocalDateTime getSubmittedAt() { return submittedAt; }

    /**
     * Sets the date and time when the submission was made.
     *
     * @param submittedAt the submission timestamp to set
     */
    public void setSubmittedAt(LocalDateTime submittedAt) { this.submittedAt = submittedAt; }

    /**
     * Returns the grade assigned to the submission.
     *
     * @return the grade
     */
    public Integer getGrade() { return grade; }

    /**
     * Sets the grade assigned to the submission.
     *
     * @param grade the grade to set
     */
    public void setGrade(Integer grade) { this.grade = grade; }

    /**
     * Returns the feedback provided for the submission.
     *
     * @return the feedback
     */
    public String getFeedback() { return feedback; }

    /**
     * Sets the feedback for the submission.
     *
     * @param feedback the feedback to set
     */
    public void setFeedback(String feedback) { this.feedback = feedback; }
}
