package org.example.esubmission.model;

import jakarta.persistence.*;
import org.example.esubmission.util.UserRole;

/**
 * Represents a user of the e-submission system.
 * <p>
 * This entity is mapped to the {@code users} table in the database and
 * stores authentication and role-related information for each user.
 * </p>
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for the user.
     * <p>
     * This value is automatically generated by the database using
     * identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name of the user.
     * <p>
     * This field is mandatory and cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private String name;

    /**
     * Email address of the user.
     * <p>
     * This field must be unique and is used for user identification
     * and authentication.
     * </p>
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Encrypted password of the user.
     * <p>
     * This field should never store plain-text passwords.
     * </p>
     */
    @Column(nullable = false)
    private String password;

    /**
     * Role assigned to the user.
     * <p>
     * The role determines the permissions and access level of the user
     * within the system. Defaults to {@link UserRole#STUDENT}.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    private UserRole role = UserRole.STUDENT;

    /**
     * Phone number of the user.
     * <p>
     * This field is optional and may be {@code null}.
     * </p>
     */
    @Column(nullable = true)
    private String phone;

    @Column(name = "is_email_verified", nullable = false)
    private boolean emailVerified = false;

    @Column(name = "is_phone_verified", nullable = false)
    private boolean phoneVerified = false;

    @Column(name = "two_factor_enabled", nullable = false)
    private boolean twoFactorEnabled = false;

    @Column(name = "verification_code")
    private String verificationCode;

    @Column(name = "verification_expiry")
    private java.time.LocalDateTime verificationExpiry;

    @Column(name = "reset_token")
    private String resetToken;

    @Column(name = "reset_token_expiry")
    private java.time.LocalDateTime resetTokenExpiry;

    /**
     * Returns the unique identifier of the user.
     *
     * @return the user ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the user.
     *
     * @param id the user ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the full name of the user.
     *
     * @return the user's name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the full name of the user.
     *
     * @param name the user's name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the email address of the user.
     *
     * @return the user's email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the user.
     *
     * @param email the user's email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the user's password.
     *
     * @return the encrypted password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user's password.
     *
     * @param password the encrypted password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the role assigned to the user.
     *
     * @return the user role
     */
    public UserRole getRole() {
        return role;
    }

    /**
     * Sets the role of the user.
     *
     * @param role the user role to assign
     */
    public void setRole(UserRole role) {
        this.role = role;
    }

    /**
     * Returns the phone number of the user.
     *
     * @return the user's phone number, or {@code null} if not provided
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the phone number of the user.
     *
     * @param phone the user's phone number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public boolean isEmailVerified() {
        return emailVerified;
    }

    public void setEmailVerified(boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    public boolean isPhoneVerified() {
        return phoneVerified;
    }

    public void setPhoneVerified(boolean phoneVerified) {
        this.phoneVerified = phoneVerified;
    }

    public boolean isTwoFactorEnabled() {
        return twoFactorEnabled;
    }

    public void setTwoFactorEnabled(boolean twoFactorEnabled) {
        this.twoFactorEnabled = twoFactorEnabled;
    }

    public String getVerificationCode() {
        return verificationCode;
    }

    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }

    public java.time.LocalDateTime getVerificationExpiry() {
        return verificationExpiry;
    }

    public void setVerificationExpiry(java.time.LocalDateTime verificationExpiry) {
        this.verificationExpiry = verificationExpiry;
    }

    public String getResetToken() {
        return resetToken;
    }

    public void setResetToken(String resetToken) {
        this.resetToken = resetToken;
    }

    public java.time.LocalDateTime getResetTokenExpiry() {
        return resetTokenExpiry;
    }

    public void setResetTokenExpiry(java.time.LocalDateTime resetTokenExpiry) {
        this.resetTokenExpiry = resetTokenExpiry;
    }
}
